a test code
pycasbin/redis-watcher pull request #2
Opened 2021-06-02 05:14 UTC by captt-g

2021-06-02 05:15 UTC, hsluoyz commented
@captt-g 

1. Plz use English.
2. Write good commit message.

2021-06-02 06:34 UTC, YihuiLu commented on redis_watcher/main.py
> +            user=self.db,
This should be a BUG, because Redis does not have a user parameter

2021-06-02 10:08 UTC, captt-g commented
@YihuiLu sry, I accidentally read it wrong, already fixed it.

2021-06-02 13:10 UTC, hsluoyz commented
@Zxilly plz review.

/cc @techoner

2021-06-03 11:09 UTC, techoner commented
@captt-g This is not complete, right? After receiving the message from redis, there is no callback processing

2021-06-03 11:10 UTC, techoner requested changes
After receiving the message from redis, do callback processing .

2021-06-03 14:13 UTC, captt-g commented
@techoner Yes, now I add the default update_callback() func, you can use it like red_watcher.set_update_callback(red_watcher.update_callback),thanks for your review.

2021-06-03 14:40 UTC, techoner commented
@captt-g Please refer to Go and Nodejs:

https://github.com/casbin/redis-watcher
https://github.com/node-casbin/redis-watcher

2021-06-05 03:01 UTC, hsluoyz commented
@captt-g hi, who are you? Are you applying for Summer 2021 or just for open source contribution?

2021-06-05 03:23 UTC, Zxilly commented
@hsluoyz He is applying for Summer 2021

2021-06-05 12:25 UTC, captt-g commented
@captt-g Now run the test.py, I can get message like 
![image](https://user-images.githubusercontent.com/82822713/120891624-266dce80-c63c-11eb-8f9a-c0af72b012e9.png)
,plz review, if there are something wrong, I will fix it.

2021-06-05 12:30 UTC, captt-g commented
@techoner Now run the test.py, I can get message like 
![4E18169A-85CD-4938-BF4C-573474D0B3E1](https://user-images.githubusercontent.com/82822713/120891758-d6433c00-c63c-11eb-9c5b-9dfacfdb2983.png)
,plz review, if there are something wrong, plz tell me, I will fix it.

2021-06-05 12:32 UTC, captt-g commented
@hsluoyz Hi,I'm applying for Summer 2021.

2021-06-05 13:36 UTC, hsluoyz commented
@captt-g plz contact community as: https://github.com/casbin/Summer2021#%E6%8A%95%E9%80%92%E8%A6%81%E6%B1%82

2021-06-09 05:44 UTC, Zxilly commented
@captt-g please remove `.idea` files.

2021-06-10 05:15 UTC, hsluoyz commented
@captt-g squash commits

2021-06-10 05:48 UTC, ffyuanda commented
@captt-g before claiming your work, do you need to consult the original author of these codes? [https://github.com/ScienceLogic/pycasbin-redis-watcher]()

2021-06-10 05:59 UTC, captt-g commented
@ffyuanda I have refer to his code ,but not copy word to word, his code isn't work because long time no vindicate.

2021-06-10 06:05 UTC, ffyuanda commented
@captt-g I'm not saying you are plagiarizing, it is all open-sourced. My thought is it will look better if you claim it more obviously and accredit some of the work back to the original repo. Your work is good.

2021-06-10 06:15 UTC, captt-g commented
@ffyuanda  I don't think it's necessary.Because I also refer to many other repo ,like https://github.com/casbin/redis-watcher and https://github.com/pycasbin/postgresql-watcher,they are also very useful.But my mind runs through my work.

2021-06-10 06:39 UTC, ffyuanda commented
@captt-g good for you then

2021-06-10 06:55 UTC, captt-g commented
@ffyuanda Thanks, I have add the repo I have refer to in the file commits now.

2021-06-16 13:53 UTC, techoner requested changes

2021-06-17 02:22 UTC, closed without merging

2021-06-17 02:44 UTC, hsluoyz commented
@captt-g why close?

2021-06-17 14:31 UTC, captt-g commented
I think this work may not fulfil the requirements.